apiVersion: apps/v1
kind: Deployment
metadata:
  name: redeem-points-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redeem-points
  template:
    metadata:
      labels:
        app: redeem-points
    spec:
      containers:
        - name: redeem-points
          image: cristiancasd/leal-redeem-points
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-id-secret
                  key: AWS_ACCESS_KEY_ID

            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-key-secret
                  key: AWS_SECRET_ACCESS_KEY

            - name: AWS_DEFAULT_REGION
              value: 'us-east-1'
            - name: API_URL_SRV_EVENT
              value: 'http://event-bus-srv:8070/events'
---
apiVersion: v1
kind: Service
metadata:
  name: redeem-points-srv
spec:
  selector:
    app: redeem-points
  ports:
    - name: redeem-points
      protocol: TCP
      port: 8062
      targetPort: 8062
