name: tests-redeem-points

on: 
  pull_request:
    paths:
      - 'redeem-points/**'  



jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    services:
      kafka:
        image: wurstmeister/kafka:2.12-2.7.0
        ports:
          - 9092:9092
        environment:
          KAFKA_ADVERTISED_HOST_NAME: kafka
          KAFKA_ADVERTISED_PORT: 9092
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        depends-on:
          - zookeeper
      zookeeper:
        image: zookeeper:3.6.3
        ports:
          - 2181:2181


    steps:
      - uses: actions/checkout@v2
      - run: cd redeem-points && npm install && npm run test:ci
        env:
          AWS_DEFAULT_REGION: us-east-1   
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

              