name: tests-add-points

on: 
  pull_request:
    paths:
      - 'add-points/**'  

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: cd add-points && npm install && npm run test:ci
        env:
          AWS_DEFAULT_REGION: us-east-1   
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

              